services:
    avathar.bbguildffxi.installer:
        class: avathar\bbguildffxi\game\ffxi_installer
        arguments:
            - '@dbal.conn'
            - '@cache.driver'
            - '@config'
            - '@user'

    avathar.bbguildffxi.provider:
        class: avathar\bbguildffxi\game\ffxi_provider
        arguments:
            - '@avathar.bbguildffxi.installer'
            - '@ext.manager'
        tags:
            - { name: bbguild.game_provider }
